name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Pull Request Title: $PR_TITLE"
          if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore): ]]; then
            echo "❌ Invalid PR title format. Must follow Conventional Commits (e.g., 'feat: Add new feature')."
            exit 1
          fi
        shell: bash
